/* eslint-disable */
// Generated by scripts/generate-assay-manifests.mjs. Do not edit by hand.
import type { AssayManifest } from '@/lib/assay-manifests'

export const generatedAssayManifests: AssayManifest[] = [
  {
    id: "apol1-risk",
    title: "APOL1 Risk Classifier",
    subtitle: "Classify APOL1 G0, G1, and G2 haplotype combinations from three defining sites.",
    summary: "Classify APOL1 G0, G1, and G2 haplotype combinations from three defining sites.",
    description: "Classify APOL1 G0, G1, and G2 haplotype combinations from three defining sites.",
    disclaimer: "Research use only. Not medical advice.",
    category: "risk",
    tags: [
      "apol1",
      "kidney",
      "risk"
    ],
    packageVersion: "0.1.0",
    sourceOfTruth: "script",
    ui: {
      template: "risk-classifier",
      version: "1.0"
    },
    compatibility: {
      worksWith: [
        "23andme",
        "wgs",
        "vcf",
        "cram"
      ],
      assemblies: [
        "grch37",
        "grch38"
      ],
      notes: [
        "Works when all three APOL1 defining sites are present in the source data."
      ]
    },
    privacy: {
      mode: "local_only",
      uploadsData: false,
      storesResultsLocally: true,
      externalUrls: []
    },
    interpretation: {
      matched: {
        headline: "APOL1-associated signal detected",
        body: "This assay detected one or more APOL1 sites used to derive an overall APOL1 status.",
        caveat: "Interpretation depends on the full G1 and G2 pattern."
      },
      normal: {
        headline: "No flagged APOL1 signal found",
        body: "The checked APOL1 sites were present, but this assay did not detect a flagged pattern.",
        caveat: null
      },
      missing: {
        headline: "Not enough APOL1 data",
        body: "This file did not include enough APOL1 sites for a confident result.",
        caveat: "Deletion-based APOL1 G2 calls are often absent from chip-style exports."
      },
      partial: {
        headline: "Partial APOL1 result",
        body: "Some APOL1 sites were present, but the file did not cover the full assay.",
        caveat: null
      }
    },
    files: [
      "assets/assays/apol1/apol1.py",
      "assets/assays/apol1/assay.yaml",
      "assets/assays/apol1/catalogue.yaml",
      "assets/assays/apol1/variants/g2.yaml",
      "assets/assays/apol1/variants/rs60910145.yaml",
      "assets/assays/apol1/variants/rs73885319.yaml"
    ],
    bundledAssay: {
      assayAssetModuleId: require('../assets/assays/apol1/assay.yaml'),
      assayPath: "assets/assays/apol1/assay.yaml",
      fileAssetModuleIds: {
        "assets/assays/apol1/apol1.py": require('../assets/assays/apol1/apol1.py'),
        "assets/assays/apol1/assay.yaml": require('../assets/assays/apol1/assay.yaml'),
        "assets/assays/apol1/catalogue.yaml": require('../assets/assays/apol1/catalogue.yaml'),
        "assets/assays/apol1/variants/g2.yaml": require('../assets/assays/apol1/variants/g2.yaml'),
        "assets/assays/apol1/variants/rs60910145.yaml": require('../assets/assays/apol1/variants/rs60910145.yaml'),
        "assets/assays/apol1/variants/rs73885319.yaml": require('../assets/assays/apol1/variants/rs73885319.yaml')
      }
    },
    assayMembers: [
      {
        gene: "APOL1",
        items: [
          {
            id: "APOL1_G1_rs73885319",
            rsid: "rs73885319",
            location: "GRCH37 chr22:36661906",
            kind: "SNV",
            ref: "A",
            alts: [
              "G"
            ],
            note: "APOL1 G1 site 1 SNV."
          },
          {
            id: "APOL1_G1_rs60910145",
            rsid: "rs60910145",
            location: "GRCH37 chr22:36662034",
            kind: "SNV",
            ref: "T",
            alts: [
              "G"
            ],
            note: "APOL1 G1 site 2 SNV."
          },
          {
            id: "APOL1_G2",
            rsid: "rs71785313",
            location: "GRCH37 chr22:36662046-36662051",
            kind: "INDEL",
            ref: "I",
            alts: [
              "D"
            ],
            note: "APOL1 G2 defining deletion."
          }
        ]
      }
    ]
  },
  {
    id: "herc2-eye-color",
    title: "HERC2 Eye Color",
    subtitle: "Classify the main HERC2 eye-color signal from one defining site.",
    summary: "Classify the main HERC2 eye-color signal from one defining site.",
    description: "Classify the main HERC2 eye-color signal from one defining site.",
    disclaimer: "Research use only. Not medical advice.",
    category: "traits",
    tags: [
      "herc2",
      "eye-color"
    ],
    packageVersion: "0.1.0",
    sourceOfTruth: "script",
    ui: {
      template: "binary-call",
      version: "1.0"
    },
    compatibility: {
      worksWith: [
        "23andme",
        "wgs",
        "vcf"
      ],
      assemblies: [
        "grch37",
        "grch38"
      ],
      notes: [
        "Checks one major HERC2 eye-color signal."
      ]
    },
    privacy: {
      mode: "local_only",
      uploadsData: false,
      storesResultsLocally: true,
      externalUrls: []
    },
    interpretation: {
      matched: {
        headline: "Eye-color signal detected",
        body: "This assay detected the main HERC2 signal associated with lighter eye color.",
        caveat: "Eye color is influenced by multiple genes."
      },
      normal: {
        headline: "No flagged signal found",
        body: "The checked site was present, but the lighter-eye-associated signal was not detected.",
        caveat: null
      },
      missing: {
        headline: "Not enough data",
        body: "This file did not include enough of the expected sites for a confident result.",
        caveat: null
      },
      partial: {
        headline: "Partial result",
        body: "Some expected rows were present, but the file did not cover the full assay.",
        caveat: null
      }
    },
    files: [
      "assets/assays/herc2/assay.yaml",
      "assets/assays/herc2/catalogue.yaml",
      "assets/assays/herc2/herc2.py",
      "assets/assays/herc2/variants/rs12913832.yaml"
    ],
    bundledAssay: {
      assayAssetModuleId: require('../assets/assays/herc2/assay.yaml'),
      assayPath: "assets/assays/herc2/assay.yaml",
      fileAssetModuleIds: {
        "assets/assays/herc2/assay.yaml": require('../assets/assays/herc2/assay.yaml'),
        "assets/assays/herc2/catalogue.yaml": require('../assets/assays/herc2/catalogue.yaml'),
        "assets/assays/herc2/herc2.py": require('../assets/assays/herc2/herc2.py'),
        "assets/assays/herc2/variants/rs12913832.yaml": require('../assets/assays/herc2/variants/rs12913832.yaml')
      }
    },
    assayMembers: [
      {
        gene: "HERC2",
        items: [
          {
            id: "HERC2_rs12913832",
            rsid: "rs12913832",
            location: "GRCH37 chr15:28365618",
            kind: "SNV",
            ref: "A",
            alts: [
              "G"
            ],
            note: "Associated with lighter eye color in the bundled HERC2 example."
          }
        ]
      }
    ]
  }
]
