export {
	desktopLabRunScenarios,
	labFormatMatrixScenarios,
	labTestFixtures,
	sharedLabTestScenarios,
	webLabRunScenarios,
	webPersistentHandleScenarios,
	webReportMatrixScenarios,
	type LabFormatMatrixScenario as LabTestScenario,
	type LabTestAction,
	type LabTestGenomeKind,
	type LabTestPlatform,
	type LabTestSource,
	type SharedLabTestScenario,
} from '@/tests/lab-scenarios'
