[package]
name = "biovault_rust_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.32", features = ["bundled"] }
zip = "2.2"
chrono = { version = "0.4", features = ["serde"] }
jni = "0.21.1"

[lib]
crate-type = [
    "rlib",
    "staticlib",
    "cdylib"
]
