import { StyleSheet } from 'react-native'
import { colors } from './shared'

export const researchStyles = StyleSheet.create({
	promoCard: {
		backgroundColor: colors.surface,
		marginHorizontal: 20,
		marginBottom: 20,
		padding: 24,
		borderRadius: 16,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	promoHeader: {
		alignItems: 'center',
		marginBottom: 24,
	},
	promoTitle: {
		fontSize: 24,
		fontWeight: '700',
		color: colors.textPrimary,
		marginBottom: 8,
		textAlign: 'center',
	},
	promoSubtitle: {
		fontSize: 16,
		color: colors.textSecondary,
		textAlign: 'center',
		lineHeight: 22,
	},
	benefitsList: {
		marginBottom: 24,
	},
	benefitCard: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: colors.surface,
		padding: 16,
		borderRadius: 12,
		marginBottom: 12,
		borderWidth: 1,
		borderColor: '#e0e0e0',
	},
	benefitIconContainer: {
		width: 44,
		height: 44,
		borderRadius: 22,
		backgroundColor: '#f0f8f0',
		justifyContent: 'center',
		alignItems: 'center',
		marginRight: 12,
	},
	benefitIcon: {
		fontSize: 20,
	},
	benefitContent: {
		flex: 1,
	},
	benefitTitle: {
		fontSize: 16,
		fontWeight: '600',
		color: colors.textPrimary,
		marginBottom: 2,
	},
	benefitDescription: {
		fontSize: 13,
		color: colors.textSecondary,
		lineHeight: 18,
	},
	benefitArrow: {
		width: 24,
		height: 24,
		borderRadius: 12,
		backgroundColor: colors.primary,
		justifyContent: 'center',
		alignItems: 'center',
		marginLeft: 8,
	},
	arrowText: {
		fontSize: 12,
		color: colors.surface,
		fontWeight: '600',
	},
	installButton: {
		backgroundColor: colors.primary,
		paddingVertical: 16,
		borderRadius: 12,
		alignItems: 'center',
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 4 },
		shadowOpacity: 0.2,
		shadowRadius: 8,
		elevation: 4,
	},
	installButtonText: {
		fontSize: 18,
		fontWeight: '700',
		color: colors.surface,
	},
	guideCard: {
		backgroundColor: colors.surface,
		marginHorizontal: 20,
		marginBottom: 20,
		padding: 20,
		borderRadius: 16,
		borderWidth: 2,
		borderColor: colors.primary,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	guideHeader: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginBottom: 20,
	},
	guideTitle: {
		fontSize: 20,
		fontWeight: '700',
		color: colors.textPrimary,
	},
	closeButton: {
		fontSize: 18,
		color: colors.textSecondary,
		fontWeight: '600',
	},
	stepCard: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		marginBottom: 16,
	},
	stepNumber: {
		width: 28,
		height: 28,
		borderRadius: 14,
		backgroundColor: colors.primary,
		color: colors.surface,
		fontSize: 14,
		fontWeight: '700',
		textAlign: 'center',
		lineHeight: 28,
		marginRight: 12,
	},
	stepContent: {
		flex: 1,
	},
	stepTitle: {
		fontSize: 16,
		fontWeight: '600',
		color: colors.textPrimary,
		marginBottom: 4,
	},
	stepDescription: {
		fontSize: 14,
		color: colors.textSecondary,
		lineHeight: 18,
	},
	visitWebsiteButton: {
		backgroundColor: colors.primary,
		paddingVertical: 12,
		borderRadius: 8,
		alignItems: 'center',
		marginTop: 8,
	},
	visitWebsiteButtonText: {
		color: colors.surface,
		fontSize: 16,
		fontWeight: '600',
	},
	networkOverview: {
		marginHorizontal: 20,
		marginBottom: 20,
	},
	overviewTitle: {
		fontSize: 20,
		fontWeight: '700',
		color: colors.textPrimary,
		marginBottom: 16,
	},
	workflowCard: {
		backgroundColor: colors.surface,
		padding: 20,
		borderRadius: 12,
		marginBottom: 12,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.1,
		shadowRadius: 4,
		elevation: 3,
	},
	workflowTitle: {
		fontSize: 16,
		fontWeight: '700',
		color: colors.textPrimary,
		marginBottom: 12,
	},
	workflowStep: {
		fontSize: 14,
		color: colors.textSecondary,
		marginBottom: 8,
		lineHeight: 18,
	},
})