name: CI

on:
  pull_request:
    branches: [ main, develop ]
  # Optionally, allow manual trigger for debugging
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: biovault_rust_lib
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Show Rust versions
        run: |
          rustc --version
          cargo --version
          rustfmt --version

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('biovault_rust_lib/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('biovault_rust_lib/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v4
        with:
          path: biovault_rust_lib/target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('biovault_rust_lib/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy (all targets)
        run: cargo clippy --all-targets --all-features --no-deps -- -D warnings

      - name: Run tests
        run: cargo test --verbose

      - name: Build
        run: cargo build --verbose

